config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root                  'static_pages#home'
  get    'help'      => 'static_pages#help'
  get    'about'     => 'static_pages#about'
  get    'contact'   => 'static_pages#contact'
  get    'signup'    => 'users#new'
  post   'signup'    => 'users#create'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
    
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    validates :surname, presence: true, length: { maximum: 50 }
    validates :age, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :surname, :age, :email, :home_address, :password, :password_confirmation)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="https://moodle.griffith.ie/user/view.php?id=82619&course=11239/">Michael Hart</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class ="nav navbar-nav navbar-right">
            <li><%= link_to "Home",    root_path %></li>
            <li><%= link_to "Help",    help_path %></li>
            <li><%= link_to "Log in",  login_path %></li>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <% javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<h1><%= yield(:title) %></h1>
	<p>
		This website is my first one made using the Ruby on Rails framework.</br>
		Not so bad...</br></br>
		
		All the credits for the tutorial to Michael Hart.
	</p>
</body>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<h1><%= yield(:title) %></h1>
	<p>
		Phone: +33688427634</br>
		Mail: yoan.grandjacques@griffith.ie</br>
		Skype: yoangrandjacques</br>
	</p>
</body>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<h1><%= yield(:title) %></h1>
	<p>
		Why do you need help ? IT'S A SAMPLE APP !
	</p>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<div class="center jumbotron">
		<h1>Welcome to the Sample App</h1>
		
		<h2>
			This is the home page for the
			<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
			sample application.
		</h2>
		
		<%= link_to "Sign up now !", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
	
	<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org' %>
</body>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        
        <%= f.label :surname %>
        <%= f.text_field :surname, class: 'form-control' %>
        
        <%= f.label :age %>
        <%= f.number_field :age, class: 'form-control' %>
        
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        
        <%= f.label :home_address %>
        <%= f.text_field :home_address, class: 'form-control' %>
        
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        
        <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
    <%= @user.surname %>
    </br>
    <%= @user.age %>
    </br>
    <%= @user.email %>
    </br>
    <%= @user.home_address %>
</h1>